files:
  - source: /APKInstaller/APKInstaller/Assets/About/About.en-US.md
    translation: /APKInstaller/APKInstaller/Assets/About/About.%locale%.md
  - source: /APKInstaller/APKInstaller/Strings/en-US
    translation: /APKInstaller/APKInstaller/Strings/%locale%/%original_file_name%
