files:
  - source: /Documents/Tutorials/How To Connect WSA/How To Connect WSA.md
    translation: /Documents/Tutorials/How To Connect WSA/How To Connect WSA.%locale%.md
  - source: /Documents/Announcements/Announcements.XAML
    translation: /Documents/Announcements/Announcements.%locale%.XAML
