name: Bug report
description: Create a report to help us improve
title: "Bug title"
labels: [bug]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please enter a short, clear description of the bug.
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps to reproduce the bug
      description: Please provide any required setup and steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a description of what you expected to happen
  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem
  - type: dropdown
    validations:
      required: true
    attributes:
      label: App version
      description: Specify the version of APK Installer you're using.
      options:
        - "0.1.28"
        - "0.1.27"
        - "0.1.26"
        - "0.1.25"
        - "0.1.24"
        - "0.1.23"
        - "0.1.22"
        - "0.1.21"
        - "0.1.20"
        - "0.1.19"
        - "0.1.18"
        - "0.1.17"
        - "0.1.16"
        - "0.1.15"
        - "0.1.14"
        - "0.1.13"
        - "0.1.12"
        - "0.1.11"
        - "0.1.10"
        - "0.1.9"
        - "0.1.8"
        - "0.1.7"
        - "0.1.6"
        - "0.1.5"
        - "0.1.4"
        - "0.0.3"
        - "0.0.2"
        - "0.0.1"
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Windows version
      description: Which Windows versions did you see the issue on?
      options:
        - "Insider Build (xxxxx)"
        - "Windows 11 version 22H2 (22621, 2022 Update)"
        - "Windows 11 version 21H2 (22000)"
        - "Windows 10 version 22H2 (19045, 2022 Update)"
        - "Windows 10 version 21H2 (19044, November 2021 Update)"
        - "Windows 10 version 21H1 (19043, May 2021 Update)"
        - "Windows 10 version 20H2 (19042, October 2020 Update)"
        - "Windows 10 version 2004 (19041, May 2020 Update)"
        - "Windows 10 version 1909 (18363, November 2019 Update)"
        - "Windows 10 version 1903 (18362, May 2019 Update)"
        - "Windows 10 version 1809 (17763, October 2018 Update)"
  - type: dropdown
    validations:
      required: true
    attributes:
      label: Android device
      description: Which kind of Android device did you connect?
      options:
        - "Windows Subsystem for Android™"
        - "Android Studio Emulator"
        - "Anbox - Android in a Box"
        - "BlueStacks"
        - "Waydroid"
        - "华为移动应用引擎"
        - "Nomal Device"
        - "Other Emulator"
  - type: textarea
    attributes:
      label: Additional context
      description: Enter any other applicable info here
